name: Microservice Template Continuous Integration

on:
  pull_request:
  pull_request_target:

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    name: 'Run unit tests'
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: echo ${{ secrets.TEST_SECRET }}
